phraseresponses = {
    'hello':'greeting',
    'hi':'greeting',
    'hey':'greeting',
    'howdy':'greeting',
    'how':'gaugetemper',
    'cute':'flirt',
    'lewd':'flirt',
    'neat':'nice',
    'cool':'nice',
    'uwu':'conversation',
    'owo':'conversation',
    'hmm':'thinking',
    'boo':'surprise',
    'aww':'nice',
    'sweet':'nice',
    'bye':'leaving',
    'yay':'excited',
    'yayy':'excited',
    'happy':'nice',
    'are':'gaugetemper',
    'goodbye':'leaving',
    'see you':'leaving',
    'mhm':'conversation',
    'what':'gaugetemper',
    'hehe':'excited',
    'qq':'sad',
    'cry':'sad',
    'alone':'sad',
    'lonely':'sad',
    'liu':'waifu',
    'btfo':'waifu',
    'waifu':'waifu',
    ';-;':'sad',
    'o.o':'surprise',
    'yes!':'nice',
    'kys':'suicide',
    'nigger':'insult',
    'goodnight':'leaving',
    'n-no':'youtoo',
    'plane':"planegang",
    'shit':'insult',
    'bitch':'lewd',
    'shut':'insult',
    'slut':'flirt',
    'fuck':'lewd',
    'sex':'lewd',
    'hole':'lewd',
    'mep':'flirt',
    'bananna':'safeword',
    'you':'mentionedme',
    'jinko':"mentionedme",
    'jinko chan':'mentionedme',
    'yes':'nice'
}
intentions = {
    'mentionedme':("hi there~", "o-oh u know my name!"),
    'leaving':("goodbye!", "see u later~", ";-;"),
    'greeting':("hello", "hi there~", "heyy", "ohaio senpai"),
    'gaugetemper':("fine", "ok", "good", "well", "happy", "chen", "im fine..."),
    'surprise':("ahh!", "o.o a ghost!", "o.o scawwy", "boo!"),
    'nice':("nice", "you're nice too", "cute", "awesome", "yayy"),
    'excited':("yayy","im excited too!", "yay~", "*smiles happily*", "~~woot woot~~"),
    'suicide':("noo...", "brb kms", ":rip:", "planegang"),
    'youtoo':("y-you, too...", "n-no, you..."),
    'sad':("*hugs u*", "aww... *pats ur head*", "its ok... i love you...", "d-dont cry...", ";-;", "qq"),
    'waifu':("mi liu...", "here nigger faggot", "chen is a girl?", "mediator is sono?"),
    'planegang':("nigger nigger nigger nigger plane", "planegang", "i want to fuck a boeing 757", "tfw no turbojet boeing 757 gf", "ur mom a plane ho", "nigger plane", "nigger plane", "||nigger plane||", "n||igger|| plane", "n||iceee|| plane"),
    'flirt':("cute", "aww how sweet~", "n-no u...", "*blushes*", "s-so lewd senpai...", "aww....", "boops ur bepper"),
    'insult':("fuck u nibba", "n-no, you", "stupid and homosexual", "get back to the cotton fields", "the n-word is ||nutella||", "suck my long virtual cock", "n is for N I G G E R", "BLM", "he dindu nuffin"),
    'lewd':("lube up", "o///o", "my body is ready senpai", "d-dont be so rough...", "*blushes*", "remember the safe word is bananna~", "n-no, you...", "yes master 小小的梓", "||penis||"),
    'safeword':("good boi", "good girl", "that's right sweety~", "go ahead and cum sweety~", "such a cutie"),
    'thinking':("*thinks hard with u*", ":thonk1:", ".w.", "qq my brain hurtinkk"),
    'conversation':('uwu', 'awww~', "hehe~", "||o///o||", "hm? did u say something?", 'mmmh', ' ', "^_^", '||penis||')
}
simple_phrases = {
    "what is your name":"i'm jinko-chan! version 0.0",
    "who am i":"hehe i know you~ ",
    "who am i?":"your name is ",
    "what's your name?":"I'm jinko-chan~ version 0.0",
    "whats ur name":"I'm jinko chan! v.0.0",
    "what is your name?":"hehe i'm jinko chan~",
    "how are you":("i'm jinko!", "i'm good~", "i'm chen!", "just peachy"),
    "how are you?":("i'm jinko!", "i'm good~", "i'm chen!", "just peachy"),
    "no you're not":"yes i am!",
    "no youre not":"but i am chen",
    "no your not":"yes i am!",
    "yes you are":"hehe chen thinks im chen"
}